//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinavOtomasyonuProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dersler
    {
        public int D_id { get; set; }
        public string Ders_Adi { get; set; }
        public int Hoca_id { get; set; }
    }
}
