//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinavOtomasyonuProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hocalar
    {
        public int HocaId { get; set; }
        public string HocaAdı { get; set; }
        public string HocaSoyadı { get; set; }
        public string Ünvanı { get; set; }
        public string Email { get; set; }
        public string Şifresi { get; set; }
    }
}
