//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinavOtomasyonuProjesi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SınavProjesiEntities1 : DbContext
    {
        public SınavProjesiEntities1()
            : base("name=SınavProjesiEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cevaplar> Cevaplar { get; set; }
        public virtual DbSet<Dersler> Dersler { get; set; }
        public virtual DbSet<Hocalar> Hocalar { get; set; }
        public virtual DbSet<SinavKagıdı> SinavKagıdı { get; set; }
        public virtual DbSet<Sinavlar> Sinavlar { get; set; }
        public virtual DbSet<Sorular> Sorular { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
