//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinavOtomasyonuProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sinavlar
    {
        public int Sınav_id { get; set; }
        public string SınavTipi { get; set; }
        public System.DateTime SınavTarihi { get; set; }
        public string DersAdi { get; set; }
        public int S_Hoca_id { get; set; }
    
        public virtual SinavKagıdı SinavKagıdı { get; set; }
    }
}
