//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinavOtomasyonuProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinavKagıdı
    {
        public int SinavKagidiId { get; set; }
        public int SoruId { get; set; }
        public Nullable<int> CevapId { get; set; }
        public int SınavId { get; set; }
    
        public virtual Cevaplar Cevaplar { get; set; }
        public virtual Sinavlar Sinavlar { get; set; }
        public virtual Sorular Sorular { get; set; }
    }
}
